language: python

notifications:
  email: false

os:
  - linux
  # - windows

python:
  - "3.7"
  - "3.8"

install:
  - sudo apt-get install gnutls-dev
  - pip install -e .[dev]

script:
  - ./tests/run_mypy.sh
