language: python

python:
  - "3.7"
  - "3.8"

install:
  - sudo apt-get install gnutls-dev
  - pip install -e .[dev]

stages:
  - test

jobs:
  include:
    - stage: test
      name: "mypy"
      script: ./tests/run_mypy.sh
