name: Purge cached README images

on: [ workflow_call ]

permissions:
  contents: read

jobs:
  purge-readme-images:
    # TODO: consider if we actually need this step?
    if: github.repository_owner == 'tuokri'

    runs-on: ubuntu-latest

    env:
      REPO_URL: https://github.com/${{ github.repository }}
      FULL_URL: $REPO_URL/tree/${{ github.ref_name }}

    steps:
      - name: Log env
        shell: bash
        run: |
          echo "REPO_URL: $REPO_URL"
          echo "FULL_URL: $FULL_URL"

      - name: Purge all cached camo images
        shell: bash
        run: |
          urls=$(curl -sLk ${{ env.FULL_URL }} | grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")

          while IFS= read -r line; do curl -X PURGE $line ; done <<< $urls
